output_fold: /home/zhouchi/raw_data/mel_wes_result/mel_21_1
itunes_bin_path: /home/zhouchi/project/immunotherapy/neoantigen_pipeline/iTuNES-dev/bin
tumor_fastq_path_first: /home/zhouchi/raw_data/phs001005/fastq/SRR2672888/SRR2672888_1.fastq
tumor_fastq_path_second: /home/zhouchi/raw_data/phs001005/fastq/SRR2672888/SRR2672888_2.fastq
normal_fastq_path_first: /home/zhouchi/raw_data/phs001005/fastq/SRR2672887/SRR2672887_1.fastq
normal_fastq_path_second: /home/zhouchi/raw_data/phs001005/fastq/SRR2672887/SRR2672887_2.fastq
opitype_fold: /home/zhouchi/software/OptiType/OptiTypePipeline.py
sample_name: mel_21_1
thread_number: 16
reference_path: /home/zhouchi/database/Annotation/Fasta/human.fasta
bwa_index_path: /home/zhouchi/database/Annotation/Index/bwa/human
genome: human
bwa_path: /home/zhouchi/bin/bwa
samtools_path: /home/zhouchi/bin/samtools
java_picard_path: /home/zhouchi/software/gatk_pre/picard-tools-2.3.0/picard.jar
GATK_path: /home/zhouchi/software/gatk_pre/GenomeAnalysisTK.jar
dbsnp138: /home/zhouchi/database/Annotation/hg38_vcf/dbsnp_138.hg38.vcf.gz
hapmap: /home/zhouchi/database/Annotation/hg38_vcf/hapmap_3.3.hg38.vcf.gz
omni: /home/zhouchi/database/Annotation/hg38_vcf/1000G_phase1.snps.high_confidence.hg38.vcf.gz
OneKG: /home/zhouchi/database/Annotation/hg38_vcf/1000G_omni2.5.hg38.vcf.gz
mills: /home/zhouchi/database/Annotation/hg38_vcf/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
cosmic: /home/zhouchi/database/Annotation/hg38_vcf/CosmicCodingMuts_chr_M_sorted.vcf.gz
vep_cache_path: /home/zhouchi/database/Annotation/vep_data/
hla_str: HLA-A02:01
expression_file: None
binding_fc_aff_cutoff: 1
binding_aff_cutoff: 500
fpkm_cutoff: 0
varscan_path: /home/zhouchi/software/varscan/VarScan.v2.4.2.jar
vep_path: /usr/local/ensembl-vep/vep
netMHCpan_path: /home/zhouchi/bin/netMHCpan
pyclone_path: /usr/local/bin/PyClone
coverage_cutoff: 10
strelka_path: /usr/local/bin
tumor_rna_fastq_1: /home/zhouchi/raw_data/phs001005/fastq/SRR2672889/SRR2672889_1.fastq
tumor_rna_fastq_2: /home/zhouchi/raw_data/phs001005/fastq/SRR2672889/SRR2672889_2.fastq
kallisto_path: /home/zhouchi/bin/kallisto
kallisto_cdna_path: /home/zhouchi/database/Annotation/Fasta/Homo_sapiens.GRCh38.cdna.all.fa
trimmomatic_path: /home/zhouchi/software/Trimmomatic-0.36/trimmomatic-0.36.jar
adapter_path: /home/zhouchi/software/Trimmomatic-0.36/adapters/TruSeq3-PE.fa
vcftools_path: /usr/bin/vcftools
iedb_seq_file: /home/zhouchi/database/Annotation/protein/iedb.fasta
postive_pep_file: /home/zhouchi/database/Annotation/protein/HLA-A*02-01_postive.txt
negative_pep_file: /home/zhouchi/database/Annotation/protein/HLA-A*02-01_negative.txt
